os:
  - linux
  - osx

dist: xenial # Ubuntu 16.04

osx_image: xcode9.3 # macOS 10.13

language: clojure
lein: lein
jdk:
    - openjdk8
    - openjdk11

services:
  - xvfb

script: ./test.sh

# https://github.com/travis-ci/travis-ci/issues/3897
#branches:
#    only:
#        - master
#        - /\d+\.\d+\.\d+/

jobs:
    include:
        # run the release stage 
        # when the branch being tested is 'master'
        # and the revision has been tagged
        -   
            stage: release
            jdk: openjdk8
            if: tag IS present
            script: ./release.sh
            deploy:
                provider: releases
                api_key: $GITHUB_TOKEN
                file_glob: true
                file: 
                    - "target/wowman-*-standalone.jar" # target/wowman-1.1.1-standalone.jar
                    - "target/wowman-*-standalone.jar.sha256" # target/wowman-1.1.1-standalone.jar.sha256
                skip_cleanup: true
                # redundant if "if: tag is present" ?
                on:
                    tags: true
